### ISSUE TITLE
Add crop selection to field creation

### ISSUE THREAD

**Issue by Alecsen** [Alecsen/SmartFarmer#51]
A user should be able to add a crop type and field name, when creating a field. 

When a user has marked a area and presses the button "tilføj mark". A pop should occur, and a user should be asked to insert a field name, and choose a crop type from a list of values, staticly made in the front end. 

DB: 
- Create a importance and crop varible in field. 
Application 
- Add the properties the the DTO

**Comment by lKrollo** [comment]
on it
